apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: traefik-ingress
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: hello.89c360e5-5b6d-49b3-b43d-33c5a9f94213.k8s.civo.com
    http:
      paths:
      - path: /
        backend:
          serviceName: react-app-service
          servicePort: 3000
